<a href="https://colab.research.google.com/github/sreya881/MINI-PROJECT/blob/main/event_eligibility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving events_dataset_cleaned_names_links (1).xlsx to events_dataset_cleaned_names_links (1).xlsx

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_excel("/content/events_dataset_cleaned_names_links (1).xlsx")

In [ ]:
df.columns = df.columns.str.strip()
df["skills"] = df["skills"].str.lower()
df["region"] = df["region"].str.lower()
df["mode"] = df["mode"].str.lower()
df["type"] = df["type"].str.lower()

In [ ]:
print(df.columns)

Index(['event id', 'name', 'type', 'organizer', 'region', 'min_gpa', 'course',
       'skills', 'deadline', 'mode', 'link'],
      dtype='object')

In [ ]:
display(df.head())

,event id,name,type,organizer,region,min_gpa,course,skills,deadline,mode,link
0,1,kerala internship portal,internship,higher education council,kerala,7.0,UG,"research ,ms office",ongoing,online/offline,https://internshipkerala.org
1,2,LSGD Internship,internship,local self govt dept,kerala,6.5,UG/PG,"administration,communication",ongoing,offline,https://lsgdinternship.kerala.gov.in
2,3,vijnana keralam internship,internship,kerala govt.&K-DISC,kerala,7.5,UG/PG,"science,lab work",2025-07-09 00:00:00,field,"https://vijanakerala,kerala.gov.in"
3,4,academic internship program,internship,kerala startup mission,kerala,7.0,UG/PG,"coding,research",rolling,offline,https://aip.startupmission.in
4,5,IEDC startup internship,internship,KSUM,kerala,7.5,UG/PG,coding,rolling,offline,https://startupmission.kerala.gov.in

In [ ]:
def check_eligibility(student_gpa, student_region, student_skills, student_mode=None):

    student_region = student_region.lower()
    student_skills = [s.lower().strip() for s in student_skills]

    eligible = []

    for index, row in df.iterrows():

        # GPA rule
        if student_gpa < row["min_gpa"]:
            continue

        # Region rule
        if not (row["region"] == "national" or row["region"] == student_region):
            continue

        # Skills rule
        event_skills = [s.strip() for s in row["skills"].split(",")]
        if not any(skill in event_skills for skill in student_skills):
            continue

        # Mode rule (optional)
        if student_mode:
            if row["mode"] != student_mode.lower():
                continue

        eligible.append(row["name"])

    return eligible

In [ ]:
results = check_eligibility(
    student_gpa=7.5,
    student_region="kerala",
    student_skills=["science", "coding"],
    student_mode="offline"
)

import pandas as pd

results_df = pd.DataFrame(results)
results_df

                              0
0   academic internship program
1       IEDC startup internship
2            Web Dev Internship
3            Web Dev Internship
4              Coding Hackathon
5               Iot Scholarship
6               Coding Workshop
7            Coding Scholarship
8               Coding Workshop
9        Innovation Scholarship
10            Cloud Scholarship
11     Cybersecurity Internship
12             Coding Hackathon